.TH "File" 3 "Sat Sep 26 2015" "Version 0.1" "Deduplicator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
File \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFile\fP (boost::filesystem::path p, int s)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBFile\fP &rhs)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "boost::filesystem::path \fBpath\fP"
.br
.ti -1c
.RI "int \fBsize\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file main\&.cpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "File::File (boost::filesystem::path p, int s)\fC [inline]\fP"

.PP
Definition at line 14 of file main\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "bool File::operator== (const \fBFile\fP & rhs)\fC [inline]\fP"

.PP
Definition at line 19 of file main\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "boost::filesystem::path File::path"

.PP
Definition at line 11 of file main\&.cpp\&.
.SS "int File::size"

.PP
Definition at line 12 of file main\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Deduplicator from the source code\&.
